[package]
name = "trillium-tls-common"
version = "0.1.0"
edition = "2018"
authors = ["Jacob Rothstein <hi@jbr.me>"]
description = "tls interfaces for trillium.rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "http", "async", "tls"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
futures-lite = "1.12.0"
async-trait = "0.1.50"
url = "2.2.2"
