[package]
name = "trillium-tokio"
version = "0.2.1"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2021"
description = "tokio runtime adapter for trillium.rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "framework", "async"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
async-compat = "0.2.1"
log = "0.4.17"
tokio-stream = { version = "0.1.12", features = ["net"] }
trillium = { path = "../trillium", version = "^0.2.0" }
trillium-http = { path = "../http", version = "^0.2.0" }
trillium-macros = { version = "0.0.4", path = "../macros" }
trillium-server-common = { path = "../server-common", version = "^0.4.0" }

[dependencies.tokio]
version = "1.26.0"
features = ["rt", "net", "fs", "rt-multi-thread", "time"]
package = "tokio"

[target.'cfg(unix)'.dependencies]
signal-hook = "0.3.15"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }

[dev-dependencies]
env_logger = "0.10.0"
tokio = { version = "1.26.0", features = ["full"], package = "tokio" }
