[workspace]
resolver = "2"
members = [
  "askama",
  "async-std-server",
  "aws-lambda",
  "aws-lambda-example",
  "basic-auth",
  "cookies",
  "cli",
  "example",
  "handlebars",
  "http",
  "logger",
  "trillium",
  "native-tls",
  "router",
  "rustls",
  "server-common",
  "sessions",
  "smol-server",
  "static",
  "static-compiled",
  "tera",
  "testing",
  "tls-common",
  "tokio-server",
  "websockets",
  "proxy",
  "client",
  "html-rewriter",
]
exclude = ["controllers"]
