[workspace]
resolver = "2"
members = [
  "api",
  "askama",
  "async-std",
  "aws-lambda",
  "aws-lambda-example",
  "basic-auth",
  "caching-headers",
  "channels",
  "client",
  "compression",
  "conn-id",
  "cookies",
  "example",
  "forwarding",
  "handlebars",
  "head",
  "http",
  "logger",
  "method-override",
  "native-tls",
  "proxy",
  "router",
  "rustls",
  "server-common",
  "sessions",
  "smol",
  "sse",
  "static",
  "static-compiled",
  "static-compiled-macros",
  "tera",
  "testing",
  "tls-common",
  "tokio",
  "trillium",
  "websockets",
]
exclude = ["controllers"]
