[package]
name = "trillium-router"
version = "0.3.6"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2021"
description = "router for trillium.rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "framework", "async", "router"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
log = "0.4.20"
routefinder = { version = "0.5.4", features = ["memchr"] }
trillium = { path = "../trillium", version = "0.2.13" }

[dev-dependencies]
env_logger = "0.11.0"
trillium-logger = { path = "../logger" }
trillium-smol = { path = "../smol" }
trillium-testing = { path = "../testing" }
