[package]
name = "trillium-router"
version = "0.1.1"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"
description = "router for trillium.rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "framework", "async", "router"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
log = "0.4.14"
routefinder = "0.3.1"
trillium = { path = "../trillium", version = "^0.1.0" }

[dev-dependencies]
env_logger = "0.8.4"
trillium-logger = { path = "../logger" }
trillium-smol = { path = "../smol" }
trillium-testing = { path = "../testing" }
