[package]
name = "trillium-aws-lambda"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
trillium = { path = "../trillium" }
log = "0.4.14"
tokio = { version = "1.6.1", features = ["rt", "net", "rt-multi-thread"] }
trillium-http = { path = "../http", version = "0.0.1" }
futures-lite = "1.11.3"
serde_json = "1.0.64"
serde = "1.0.126"
serde_derive = "1.0.126"
base64 = "0.13.0"
lamedh_runtime = "0.3.0"

[dependencies.http-types]
version = "0.0.1"
default-features = false
features = ["serde"]
package = "trillium-http-types"
