[package]
name = "trillium"
version = "0.0.1"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"
description = "a modular toolkit for building async web apps"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "README.md"
keywords = ["trillium", "framework", "async"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
async-trait = "0.1.50"
futures-lite = "1.11.3"
log = "0.4.14"
trillium-http = { path = "../http", version = "0.0.1" }

[dev-dependencies]
trillium-logger = { path = "../logger" }
trillium-testing = { path = "../testing" }
async-net = "1.6.0"
trillium-smol = { path = "../smol" }
