[package]
name = "trillium-handlebars"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
trillium = { path = "../trillium" }
glob = "0.3.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
log = "0.4.14"

[dependencies.handlebars]
version = "3.5.5"
features = ["dir_source"]

[dev-dependencies]
trillium-smol-server = { path = "../smol-server" }
env_logger = "0.8.3"
trillium-testing = { path = "../testing" }
