[package]
name = "trillium-sessions"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
trillium-cookies = { path = "../cookies" }
trillium = { path = "../trillium" }
async-session = "2.0.1"
log = "0.4.14"

[dev-dependencies]
env_logger = "0.8.3"
trillium-smol-server = { path = "../smol-server" }
trillium-testing = { path = "../testing" }
