[package]
name = "trillium-sessions"
version = "0.4.3"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2021"
description = "session storage handler for trillium.rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "framework", "async"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
trillium-cookies = { path = "../cookies", version = "0.4.1" }
trillium = { path = "../trillium", version = "0.2.13" }
async-session = "3.0.0"
log = "0.4.20"

[dev-dependencies]
env_logger = "0.11.0"
trillium-smol = { path = "../smol" }
trillium-testing = { path = "../testing" }

[package.metadata.cargo-udeps.ignore]
development = ["trillium-testing"]
