[package]
name = "trillium-server-common"
version = "0.4.5"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2021"
description = "server utilities for trillium.rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "framework", "async"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
async-trait = "0.1.72"
async_cell = "0.2.2"
event-listener = "3.0.0"
futures-lite = "2.0.0"
log = "0.4.19"
pin-project-lite = "0.2.13"
trillium = { path = "../trillium", version = "^0.2.0" }
trillium-http = { path = "../http", version = "^0.3.0" }
url = "2.4.0"

[target.'cfg(unix)'.dependencies]
rlimit = "0.10.1"

[dev-dependencies]
test-harness = "0.1.1"
trillium-smol = { path = "../smol" }
trillium-testing = { path = "../testing" }

[features]

[package.metadata.cargo-udeps.ignore]
development = ["trillium-testing", "trillium-smol"]
