[package]
name = "trillium-server-common"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
trillium = { path = "../trillium" }
trillium-http = { path = "../http" }
log = "0.4.14"
futures-lite = "1.11.3"
trillium-tls-common = { path = "../tls-common/" }
async-channel = "1.5.1"
pin-project-lite = "0.2.4"
atomic-waker = "1.0.0"

[dev-dependencies]
async-io = "1.3.1"
trillium-testing = { path = "../testing" }
