[package]
name = "trillium-http"
version = "0.1.4"
edition = "2018"
authors = ["Jacob Rothstein <hi@jbr.me>"]
description = "the http implementation for the trillium toolkit"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "http", "async"]
categories = ["web-programming::http-server", "web-programming"]

[features]
unstable = []

[dependencies]
encoding_rs = "0.8.28"
futures-lite = "1.12.0"
http-types = { version = "0.0.2", default-features = false, package = "trillium-http-types" }
httparse = "1.4.1"
log = "0.4.14"
memmem = "0.1.1"
pin-project = "1.0.7"
stopper = "0.2.0"
thiserror = "1.0.26"

[dev-dependencies]
async-compat = "0.2.1"
async-io = "1.6.0"
async-net = "1.6.1"
env_logger = "0.8.4"
smol = "1.2.5"
trillium-client = { path = "../client" }
trillium-smol = { path = "../smol" }
trillium-testing = { path = "../testing" }

[dev-dependencies.tokio]
version = "1.8.1"
features = ["rt", "net", "rt-multi-thread", "macros"]
package = "tokio"
