[package]
name = "trillium-http"
version = "0.3.6"
edition = "2021"
authors = ["Jacob Rothstein <hi@jbr.me>"]
description = "the http implementation for the trillium toolkit"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "http", "async"]
categories = ["web-programming::http-server", "web-programming"]

[features]
unstable = []
http-compat = ["http"]
serde = ["dep:serde"]

[dependencies]
encoding_rs = "0.8.33"
futures-lite = "2.0.1"
hashbrown = "0.14.2"
http = { version = "0.2.9", optional = true }
httparse = "1.8.0"
httpdate = "1.0.3"
log = "0.4.20"
memchr = "2.6.4"
mime = "0.3.17"
serde = { version = "1.0.193", features = ["derive"], optional = true }
smallvec = "1.11.2"
smartcow = "0.2.1"
smartstring = "1.0.1"
stopper = "0.2.3"
thiserror = "1.0.50"
trillium-macros = { version = "0.0.4", path = "../macros" }

[dev-dependencies]
async-compat = "0.2.3"
async-io = "2.2.0"
async-net = "2.0.0"
env_logger = "0.10.1"
smol = "1.3.0"
trillium-client = { path = "../client" }
trillium-smol = { path = "../smol" }
trillium-testing = { path = "../testing" }
trillium-http = { path = ".", features = ["http-compat"] }
pretty_assertions = "1.4.0"
fastrand = "2.0.1"
test-harness = "0.1.1"
indoc = "2.0.4"

[dev-dependencies.tokio]
version = "1.34.0"
features = ["rt", "net", "rt-multi-thread", "macros"]
package = "tokio"
