[package]
name = "trillium-static-compiled"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"
description = "compile-time static assets for trillium.rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "framework", "async"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
include_dir = "0.6.1"
log = "0.4.14"
mime-db = "1.4.0"
trillium = { path = "../trillium", version = "^0.1.0" }

[dev-dependencies]
env_logger = "0.8.4"
trillium-smol = { path = "../smol" }
trillium-testing = { path = "../testing" }
