[package]
name = "trillium-logger"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
trillium = { path = "../trillium" }
log = "0.4.14"
colored = "2.0.0"
size = "0.1.2"

[dev-dependencies]
env_logger = "0.8.3"
trillium-smol = { path = "../smol" }
