[package]
name = "trillium-websockets"
version = "0.3.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"
description = "websocket support for trillium.rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "framework", "async"]
categories = ["web-programming::http-server", "web-programming"]

[features]
json = ["serde_json", "serde"]

[dependencies]
async-dup = "1.2.2"
async-tungstenite = "0.15.0"
base64 = "0.13.0"
futures-util = "0.3.16"
log = "0.4.14"
pin-project = "1.0.8"
serde = { version = "1.0.129", optional = true }
serde_json = { version = "1.0.66", optional = true }
sha-1 = "0.9.7"
stopper = "0.2.0"
trillium = { path = "../trillium", version = "^0.2.0"}
trillium-http = { path = "../http", version = "^0.2.0" }

[dev-dependencies]
async-net = "1.6.1"
env_logger = "0.9.0"
trillium-smol = { path = "../smol" }
trillium-testing = { path = "../testing" }

[package.metadata.cargo-udeps.ignore]
development = ["trillium-testing"]
