[package]
name = "trillium-websockets"
version = "0.5.2"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2021"
description = "websocket support for trillium.rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "framework", "async"]
categories = ["web-programming::http-server", "web-programming"]

[package.metadata.docs.rs]
features = ["json"]

[features]
default = []
json = ["serde_json", "serde"]

[dependencies]
async-tungstenite = "0.24.0"
base64 = "0.21.5"
fastrand = "2.0.1"
futures-lite = "2.1.0"
futures-util = "0.3.29"
log = "0.4.20"
serde = { version = "1.0.193", optional = true }
serde_json = { version = "1.0.108", optional = true }
sha-1 = "0.10.1"
stopper = "0.2.3"
trillium = { path = "../trillium", version = "0.2.0" }
trillium-http = { path = "../http", version = "0.3.7" }

[dev-dependencies]
serde = { version = "1.0.193", features = ["derive"] }
async-channel = "2.1.1"
async-net = "2.0.0"
broadcaster = "1.0.0"
trillium-smol = { path = "../smol" }
trillium-testing = { path = "../testing" }
trillium-websockets = { features = ["json"], path = "." }

[package.metadata.cargo-udeps.ignore]
development = ["trillium-testing"]
