[package]
name = "trillium-proxy"
version = "0.4.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2021"
description = "reverse proxy for trillium.rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "framework", "async"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
full-duplex-async-copy = "0.1.0"
log = "0.4.17"
size = "0.4.1"
trillium = { path = "../trillium", version = "^0.2.0"}
trillium-client = { path = "../client", version = "^0.4.0" }
trillium-http = { path = "../http", version = "^0.3.0" }
url = "2.3.1"

[dev-dependencies]
env_logger = "0.10.0"
trillium-logger = { path = "../logger" }
trillium-rustls = { path = "../rustls" }
trillium-smol = { path = "../smol" }
