[package]
name = "trillium-proxy"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
trillium = { path = "../trillium" }
url = "2.2.2"
log = "0.4.14"
trillium-http = { path = "../http" }
trillium-client = { path = "../client" }
async-net = "1.6.0"
size = "0.1.2"
full-duplex-async-copy = "0.1.0"

[dev-dependencies]
trillium-smol = { path = "../smol" }
env_logger = "0.8.3"
trillium-logger = { path = "../logger" }
