[package]
name = "trillium-proxy"
version = "0.5.3"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2021"
description = "reverse proxy for trillium.rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "framework", "async"]
categories = ["web-programming::http-server", "web-programming"]

[features]
default = ["upstream-random", "upstream-connection-counting"]
upstream-random = ["dep:fastrand"]
upstream-connection-counting = ["dep:trillium-server-common", "dep:fastrand"]

[dependencies]
event-listener = "4.0.1"
fastrand = { version = "2.0.1", optional = true }
full-duplex-async-copy = "0.1.0"
futures-lite = "2.1.0"
log = "0.4.20"
size = "0.4.1"
sluice = "0.5.5"
trillium = { path = "../trillium", version = "0.2.19" }
trillium-client = { path = "../client", version = "0.6.0" }
trillium-forwarding = { version = "0.2.3", path = "../forwarding" }
trillium-http = { path = "../http", version = "0.3.16", features = ["unstable"] }
trillium-server-common = { version = "0.5.2", path = "../server-common", optional = true }
url = "2.5.0"

[dev-dependencies]
env_logger = "0.11.0"
querystrong = { version = "0.3.0", features = ["serde"] }
trillium-api = { path = "../api" }
trillium-http = { path = "../http", features = ["serde"] }
trillium-logger = { path = "../logger" }
trillium-smol = { path = "../smol" }
