[package]
name = "trillium-static"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
async-fs = "1.5.0"
trillium = { path = "../trillium" }
mime-db = "1.3.0"
futures-lite = "1.11.3"
log = "0.4.14"
relative-path = "1.4.0"

[dev-dependencies]
trillium-smol-server = { path = "../smol-server" }
trillium-testing = { path = "../testing" }
