[package]
name = "trillium-static"
version = "0.4.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2021"
description = "filesystem-backed static assets for trillium.rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "framework", "async"]
categories = ["web-programming::http-server", "web-programming"]

[features]
async-std = ["async_std_crate"]
default = []
smol = ["async-fs"]
tokio = ["tokio_crate", "async-compat"]

[dependencies]
async-compat = { version = "0.2.1", optional = true }
async-fs = { version = "1.5.0", optional = true }
cfg-if = "1.0.0"
futures-lite = "1.12.0"
log = "0.4.14"
relative-path = "1.5.0"
trillium = { path = "../trillium", version = "^0.2.0" }
mime_guess = "2.0.3"
httpdate = "1.0.1"
etag = { version = "3.0.0", features = ["std"] }

[dependencies.async_std_crate]
optional = true
package = "async-std"
version = "1.10.0"

[dependencies.tokio_crate]
features = ["fs"]
optional = true
package = "tokio"
version = "1.11.0"

[dev-dependencies]
trillium-testing = { path = "../testing" }
trillium-logger = { path = "../logger" }
trillium-smol = { path = "../smol" }

[package.metadata.cargo-udeps.ignore]
development = ["trillium-testing"]
