[package]
name = "trillium-native-tls"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2021"
description = "native-tls adapter for trillium.rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "framework", "async"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
async-native-tls = "0.4.0"
native-tls = "0.2.8"
trillium-tls-common = { path = "../tls-common", version = "^0.1.0" }

[dev-dependencies]
env_logger = "0.10.0"
trillium = { path = "../trillium" }
trillium-smol = { path = "../smol" }
