[package]
name = "trillium-native-tls"
version = "0.4.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2021"
description = "native-tls adapter for trillium.rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "framework", "async"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
async-native-tls = "0.5.0"
native-tls = "0.2.11"
trillium-server-common = { path = "../server-common", version = "0.5.2" }

[dev-dependencies]
env_logger = "0.11.0"
portpicker = "0.1.1"
test-harness = "0.2.0"
trillium = { path = "../trillium" }
trillium-client = { path = "../client" }
trillium-rustls = { path = "../rustls" }
trillium-smol = { path = "../smol" }
trillium-testing = { path = "../testing" }
