[package]
name = "trillium-tera"
version = "0.3.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2021"
description = "tera template handler for trillium.rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "framework", "async"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
log = "0.4.14"
mime-db = "1.6.0"
serde = "1.0.133"
tera = "1.15.0"
trillium = { path = "../trillium", version = "^0.2.0" }

[dev-dependencies]
trillium-smol = { path = "../smol" }
trillium-testing = { path = "../testing" }

[package.metadata.cargo-udeps.ignore]
development = ["trillium-testing"]
