[package]
name = "trillium-tera"
version = "0.3.2"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2021"
description = "tera template handler for trillium.rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "framework", "async"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
log = "0.4.20"
mime_guess = "2.0.4"
serde = "1.0.193"
tera = "1.19.1"
trillium = { path = "../trillium", version = "0.2.13" }

[dev-dependencies]
trillium-smol = { path = "../smol" }
trillium-testing = { path = "../testing" }

[package.metadata.cargo-udeps.ignore]
development = ["trillium-testing"]
