[book]
authors = ["Jacob Rothstein"]
language = "en"
multilingual = false
src = "src"
title = "trillium"

[rust]
edition = "2024"

[output.html]
git-repository-url = "https://github.com/trillium-rs/trillium"
edit-url-template = "https://github.com/trillium-rs/trillium/edit/main/docs/{path}"

[output.html.playground]
editable = false
copy-js = true
line-numbers = false
